[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"


{% if crate_type == "bin" %}
[package.metadata.v5]{% if slot != "none" %}
slot = {{ slot }}{% endif %}
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# These fields configure default behavior for uploads with `cargo v5`.

{% endif %}
icon = "{{ icon }}"
compress = true
[dependencies]
vexide = "0.3.0"
